---
#
# TODO: we must first download and reupload, as the vmware_deploy_ovf module does not support direct upload
#       to vcenter, even though the vcenter api does support it.
#
- name: 'fail if we do not provide a checksum'
  fail:
    msg: "'validate_checksum' is true but no checksum provided"
  when:
    - (validate_checksum | bool)
    - template_ova_checksum is undefined

- name: 'download the ova to a local destination'
  get_url:
    url:      "{{ template_ova_url }}"
    checksum: "{{ template_ova_checksum | default(omit) }}"
    dest:     "{{ template_ova_file }}"
  delegate_to: 'localhost'

- name: 'deploy a virtual machine from an ova'
  vmware_deploy_ovf:
    hostname:            "{{ VSPHERE_SERVER }}"
    port:                "{{ VSPHERE_PORT | default(omit) }}"
    username:            "{{ VSPHERE_USERNAME }}"
    password:            "{{ VSPHERE_PASSWORD }}"
    ova:                 "{{ template_ova_file }}"
    name:                "{{ template_name }}"
    allow_duplicates:    false
    datacenter:          "{{ VSPHERE_DATACENTER }}"
    cluster:             "{{ VSPHERE_CLUSTER | default(omit) }}"
    datastore:           "{{ VSPHERE_DATASTORE }}"
    disk_provisioning:   "{{ vsphere_disk_type | default(omit) }}"
    folder:              "{{ VSPHERE_FOLDER | default(omit) }}"
    networks:            "{{ vsphere_networks }}"  # this is a network mapping from ova to your vcenter network, e.g. 'VM Network': 'VM Network')
    power_on:            false
    wait:                false
    wait_for_ip_address: false
    validate_certs:      false
  register:      'vm_deploy_response'
  delegate_to:   'localhost'
  until:         'vm_deploy_response.instance is defined'
  retries:       3
  ignore_errors: "{{ test | bool }}"

#
# NOTE: the above and below tasks generate errors when using vcsim for testing.  only ignore errors if we explicitly pass in a test
#       parameter as true
#

- name: 'ensure the virtual machine is not a template and is powered off'
  vmware_guest:
    hostname:       "{{ VSPHERE_SERVER }}"
    port:           "{{ VSPHERE_PORT | default(omit) }}"
    username:       "{{ VSPHERE_USERNAME }}"
    password:       "{{ VSPHERE_PASSWORD }}"
    name:           "{{ template_name }}"
    is_template:    false
    state:          'present'
    datacenter:     "{{ VSPHERE_DATACENTER }}"
    cluster:        "{{ VSPHERE_CLUSTER | default(omit) }}"
    datastore:      "{{ VSPHERE_DATASTORE }}"
    folder:         "{{ vm_deploy_response.instance.hw_folder }}"
    validate_certs: false
  delegate_to:   'localhost'
  # noqa 503 : no need to run a specific handler for such a simple task
  when:          'not vm_deploy_response.changed'
  ignore_errors: "{{ test | bool }}"

- name: 'take a snapshot of the vm used for linked clone deployment'
  vmware_guest_snapshot:
    hostname:       "{{ VSPHERE_SERVER }}"
    port:           "{{ VSPHERE_PORT | default(omit) }}"
    username:       "{{ VSPHERE_USERNAME }}"
    password:       "{{ VSPHERE_PASSWORD }}"
    moid:           "{{ vm_deploy_response.instance.moid }}"
    datacenter:     "{{ VSPHERE_DATACENTER }}"
    state:          'present'
    snapshot_name:  'cluster-api pre-deploy snapshot2'
    description:    'Snapshot taken by Ansible prior to cluster-api workload cluster deployment'
    quiesce:        false
    memory_dump:    false
    validate_certs: false
  delegate_to: 'localhost'

- name: 'convert the virtual machine to a template'
  vmware_guest:
    hostname:       "{{ VSPHERE_SERVER }}"
    port:           "{{ VSPHERE_PORT | default(omit) }}"
    username:       "{{ VSPHERE_USERNAME }}"
    password:       "{{ VSPHERE_PASSWORD }}"
    name:           "{{ template_name }}"
    is_template:    true
    state:          'present'
    datacenter:     "{{ VSPHERE_DATACENTER }}"
    cluster:        "{{ VSPHERE_CLUSTER | default(omit) }}"
    datastore:      "{{ VSPHERE_DATASTORE }}"
    folder:         "{{ vm_deploy_response.instance.hw_folder }}"
    validate_certs: false
  delegate_to: 'localhost'
