---
#
# TODO: we must first download and reupload, as the vmware_deploy_ovf module does not support direct upload
#       to vcenter, even though the vcenter api does support it.
#
- name: 'get information about the virtual machine if it exists already'
  vmware_guest_info:
    hostname:            "{{ VSPHERE_SERVER }}"
    port:                "{{ VSPHERE_PORT | default(omit) }}"
    username:            "{{ VSPHERE_USERNAME }}"
    password:            "{{ VSPHERE_PASSWORD }}"
    name:                "{{ template_name }}"
    datacenter:          "{{ VSPHERE_DATACENTER }}"
    validate_certs:      false
  delegate_to: 'localhost'
  register:    'vm_info_response'
  when:        'template_name in vsphere_vm_list'

- name: 'download the ova to a local destination'
  uri:
    url:     "{{ template_ova_url }}"
    dest:    "{{ template_ova }}"
    creates: "{{ template_ova }}"
  delegate_to: 'localhost'
  when:        'template_name not in vsphere_vm_list'

- name: 'ensure the virtual machine exists and deploy if necessary'
  vmware_deploy_ovf:
    hostname:            "{{ VSPHERE_SERVER }}"
    port:                "{{ VSPHERE_PORT | default(omit) }}"
    username:            "{{ VSPHERE_USERNAME }}"
    password:            "{{ VSPHERE_PASSWORD }}"
    ova:                 "{{ template_ova }}"
    name:                "{{ template_name }}"
    allow_duplicates:    false
    datacenter:          "{{ VSPHERE_DATACENTER }}"
    cluster:             "{{ VSPHERE_CLUSTER | default(omit) }}"
    datastore:           "{{ VSPHERE_DATASTORE }}"
    disk_provisioning:   "{{ vsphere_disk_type | default(omit) }}"
    folder:              "{{ VSPHERE_FOLDER | default(omit) }}"
    networks:            "{{ vsphere_networks }}"  # this is a network mapping from ova to your vcenter network, e.g. 'VM Network': 'VM Network')
    power_on:            false
    wait:                false
    wait_for_ip_address: false
    validate_certs:      false
  register:      'vm_deploy_response'
  delegate_to:   'localhost'
  until:         'vm_deploy_response.instance is defined'
  retries:       3
  ignore_errors: 'test == true'
  when:          'template_name not in vsphere_vm_list'

- name: 'set a fact containing information about the virtual machine'
  set_fact:
    vm_info: "{{ vm_info_response.instance | default(vm_deploy_response.instance) }}"

#
# NOTE: the above and below tasks generate errors when using vcsim for testing.  only ignore errors if we explicitly pass in a test
#       parameter as true
#

- name: 'ensure the virtual machine is not a template and is powered off'
  vmware_guest:
    hostname:       "{{ VSPHERE_SERVER }}"
    port:           "{{ VSPHERE_PORT | default(omit) }}"
    username:       "{{ VSPHERE_USERNAME }}"
    password:       "{{ VSPHERE_PASSWORD }}"
    name:           "{{ template_name }}"
    is_template:    false
    state:          'present'
    datacenter:     "{{ VSPHERE_DATACENTER }}"
    cluster:        "{{ VSPHERE_CLUSTER | default(omit) }}"
    datastore:      "{{ VSPHERE_DATASTORE }}"
    folder:         "{{ vm_info.hw_folder }}"
    validate_certs: false
  delegate_to:   'localhost'
  # noqa 503 : no need to run a specific handler for such a simple task
  ignore_errors: 'test == true'

- name: 'take a snapshot of the vm used for linked clone deployment'
  vmware_guest_snapshot:
    hostname:       "{{ VSPHERE_SERVER }}"
    port:           "{{ VSPHERE_PORT | default(omit) }}"
    username:       "{{ VSPHERE_USERNAME }}"
    password:       "{{ VSPHERE_PASSWORD }}"
    moid:           "{{ vm_info.moid }}"
    datacenter:     "{{ VSPHERE_DATACENTER }}"
    state:          'present'
    snapshot_name:  'cluster-api pre-deploy snapshot2'
    description:    'Snapshot taken by Ansible prior to cluster-api workload cluster deployment'
    quiesce:        false
    memory_dump:    false
    validate_certs: false
  delegate_to: 'localhost'

- name: 'convert the virtual machine to a template'
  vmware_guest:
    hostname:       "{{ VSPHERE_SERVER }}"
    port:           "{{ VSPHERE_PORT | default(omit) }}"
    username:       "{{ VSPHERE_USERNAME }}"
    password:       "{{ VSPHERE_PASSWORD }}"
    name:           "{{ template_name }}"
    is_template:    true
    state:          'present'
    datacenter:     "{{ VSPHERE_DATACENTER }}"
    cluster:        "{{ VSPHERE_CLUSTER | default(omit) }}"
    datastore:      "{{ VSPHERE_DATASTORE }}"
    folder:         "{{ vm_info.hw_folder }}"
    validate_certs: false
  delegate_to: 'localhost'
