---
#
# KUBERNETES
#
- name:          'ensure the kubernetes templates are deployed'
  include_tasks: 'deploy.yml'
  vars:
    template_name:    "{{ VSPHERE_TEMPLATE }}"
    template_ova:     "{{ ova_download_directory }}/{{ VSPHERE_TEMPLATE }}.ova"
    template_ova_url: "{{ kubernetes_ova_url | trim }}"

#
# HA PROXY
#
- name:          'ensure the haproxy templates are deployed'
  include_tasks: 'deploy.yml'
  vars:
    template_name:    "{{ VSPHERE_HAPROXY_TEMPLATE }}"
    template_ova:     "{{ ova_download_directory }}/{{ VSPHERE_HAPROXY_TEMPLATE }}"
    template_ova_url: "{{ haproxy_ova_url | trim }}"
