name: ci

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install python
      run: |
        sudo apt-get update && \
        sudo apt-get install build-essential python3 python3-pip python3-setuptools python3-venv python3-dev

    - name: setup the virtualenv
      run: |
        python3 -m venv ansible-test-virtualenv && \
        source ansible-test-virtualenv/bin/activate

    - name: install the required python modules
      run: |
        pip3 install --upgrade pip && \
        pip3 install -r requirements.txt

    - name: install the required ansible roles
      run:  ansible-galaxy install -r requirements.yml

    - name: install go
      run: |
        sudo apt-get install wget -y && \
        wget https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz && \
        tar zxvf go1.12.7.linux-amd64.tar.gz -C ${HOME}

    - name: setup go
      run: |
        export GOROOT=${HOME}/go && \
        export GOPATH=${HOME}/go_work && \
        mkdir -p ${GOPATH} && \
        export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

    - name: install and start the vcenter simulator (vcsim)
      run: |
        go get -u github.com/vmware/govmomi/vcsim && \
        go get -u github.com/vmware/govmomi/govc && \
        nohup vcsim &

    - name: ensure vcsim is running
      run: |
        export GOVC_URL=https://user:pass@127.0.0.1:8989/sdk && \
        govc find

    - name: run ansible against the simulated vcenter environment
      run:  python3 $(which ansible-playbook) -vv site.yml -e @examples/govc.yml -e 'test=true'
