name: ci

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install python
      run:  sudo apt-get update && sudo apt-get install build-essential python3 python3-pip python3-setuptools python3-venv python3-dev

    - name: create a virtualenv
      run:  python3 -m venv ansible-test-virtualenv

    - name: source the virtualenv
      run:  source ansible-test-virtualenv/bin/activate

    - name: install the required python modules
      run:  pip3 install -r requirements.txt

    - name: install the required ansible roles
      run:  ansible-galaxy install -r requirements.yml
