name: ci

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install python
      run:  sudo apt-get update && sudo apt-get install python3 python3-pip

    - name: install virtualenv
      run:  pip3 install virtualenv && easy_install virutalenv

    - name: create a virtualenv
      run:  virtualenv -p $(which python) ansible-test-virtualenv

    - name: source the virtualenv
      run:  source ansible-test-virtualenv/usr/local/bin/activate
